{% set name = "ipynbname" %}
{% set version = "2024.1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d3c69cdee8a97814f456a7204e9cc195b4bbb4b9e45cbe757796b162493f606

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - ipykernel

test:
  imports:
    - ipynbname

about:
  home: https://github.com/msm1089/ipynbname
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Simple utility that retrieves current Jupyter notebook filename or path, when run from Jupyter notebook
  dev_url: https://github.com/msm1089/ipynbname

extra:
  recipe-maintainers:
    - DamienIrving
    - msm1089
